stages:
  - lint
  - test
  - build

.node-install: &node-install
  image: node:12
  before_script:
    - yarn install

lint:
  stage: lint
  <<: *node-install
  script:
    - yarn lint

test:
  stage: test
  <<: *node-install
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/ #https://gitlab.com/gitlab-org/gitlab-foss/-/issues/29642
  script:
    - yarn coverage

build:
  stage: build
  <<: *node-install
  script:
    - yarn build