stages:
  - lint
  - test
  - build

.node-install: &node-install
  image: node:12
  before_script:
    - yarn install

lint:
  stage: lint
  <<: *node-install
  script:
    - yarn lint

test:
  stage: test
  <<: *node-install
  script:
    - yarn test

build:
  stage: build
  <<: *node-install
  script:
    - yarn build